from crud.repositories import (
    ClassroomCRUD,
    ExamAssignmentCRUD,
    ExamCRUD,
    HomeworkCRUD,
    HomeworkReviewCRUD,
    ScenarioCRUD,
    ScenarioPushCRUD,
    StudentAbilityCRUD,
    StudentCRUD,
    UserCRUD,
    # V2 学生端
    ChatMessageCRUD,
    ChatSceneCRUD,
    ChatSessionCRUD,
    ErrorBookCategoryCRUD,
    ErrorBookEntryCRUD,
    FavoriteCategoryCRUD,
    FavoriteCRUD,
    GrammarCategoryCRUD,
    GrammarExerciseCRUD,
    GrammarSubmissionCRUD,
    LearningSessionCRUD,
    ListeningMaterialCRUD,
    SpeakingEvaluationCRUD,
    StudentKnowledgeMasteryCRUD,
    StudentVocabCollectionCRUD,
    VocabularyCRUD,
    WritingSessionCRUD,
)

__all__ = [
    # V1 教师端
    "UserCRUD",
    "ClassroomCRUD",
    "StudentCRUD",
    "StudentAbilityCRUD",
    "HomeworkCRUD",
    "HomeworkReviewCRUD",
    "ScenarioCRUD",
    "ScenarioPushCRUD",
    "ExamCRUD",
    "ExamAssignmentCRUD",
    # V2 学生端
    "ChatSceneCRUD",
    "ChatSessionCRUD",
    "ChatMessageCRUD",
    "VocabularyCRUD",
    "StudentVocabCollectionCRUD",
    "GrammarCategoryCRUD",
    "GrammarExerciseCRUD",
    "GrammarSubmissionCRUD",
    "ListeningMaterialCRUD",
    "SpeakingEvaluationCRUD",
    "WritingSessionCRUD",
    "ErrorBookCategoryCRUD",
    "ErrorBookEntryCRUD",
    "FavoriteCategoryCRUD",
    "FavoriteCRUD",
    "LearningSessionCRUD",
    "StudentKnowledgeMasteryCRUD",
]
