from models.entities import (
    Classroom,
    Exam,
    ExamAssignment,
    Homework,
    HomeworkReview,
    Scenario,
    ScenarioPush,
    Student,
    StudentAbility,
    User,
    # V2 学生端
    ChatMessage,
    ChatScene,
    ChatSession,
    ErrorBookCategory,
    ErrorBookEntry,
    Favorite,
    FavoriteCategory,
    GrammarCategory,
    GrammarExercise,
    GrammarSubmission,
    LearningSession,
    ListeningMaterial,
    SpeakingEvaluation,
    StudentKnowledgeMastery,
    StudentVocabCollection,
    Vocabulary,
    WritingSession,
)

__all__ = [
    # V1 教师端
    "User",
    "Classroom",
    "Student",
    "StudentAbility",
    "Homework",
    "HomeworkReview",
    "Scenario",
    "ScenarioPush",
    "Exam",
    "ExamAssignment",
    # V2 学生端
    "ChatScene",
    "ChatSession",
    "ChatMessage",
    "Vocabulary",
    "StudentVocabCollection",
    "GrammarCategory",
    "GrammarExercise",
    "GrammarSubmission",
    "ListeningMaterial",
    "SpeakingEvaluation",
    "WritingSession",
    "ErrorBookCategory",
    "ErrorBookEntry",
    "FavoriteCategory",
    "Favorite",
    "LearningSession",
    "StudentKnowledgeMastery",
]
